[tool.poetry]
name = "poucave"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8.5"
aiohttp = "^3.7.4"
toml = "^0.10.2"
dockerflow = "^2021.7.0"
async-timeout = "^3.0.1"
sentry-sdk = "^1.3.1"
termcolor = "^1.1.0"
aiohttp_cors = "^0.7.0"
backoff = "^1.11.1"
python-decouple = "^3.4"
logging-color-formatter = "^1.0.2"
google-cloud-bigquery = "^2.23.2"
# Extra dependencies for checks.
kinto-http = { version = "^10.7.0", optional = true }
cryptography = { version = "^3.4.7", optional = true }
websockets = { version = "^9.1", optional = true }
requests = { version = "^2.26.0", optional = true }
beautifulsoup4 = { version = "^4.9.3", optional = true }
autograph-utils = { version = "^0.1.1", optional = true }
canonicaljson-rs = { version = "^0.3.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
aioresponses = "^0.7.2"
pytest-aiohttp = "^0.3.0"
black = "^21.7b0"
flake8 = "^3.9.2"
mypy = "^0.910"
pytest-cov = "^2.12.0"
isort = "^5.9.3"
bandit = "^1.7.0"
responses = "^0.13.3"
types-toml = "^0.1.5"
types-requests = "^2.25.6"
types-termcolor = "^1.1.1"

[tool.poetry.extras]
remotesettings = [
    "kinto-http",
    "cryptography",
    "websockets",
    "requests",
    "beautifulsoup4",
    "autograph-utils",
    "canonicaljson-rs",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
